services:
  python_analysis_container:
    build: ./docker/python
    restart: always
    container_name: python_analysis_container
    volumes:
      - ./notebooks/:/root/notebooks
      - ./data/:/root/data
    ports:
      - "1234:1234"
    environment:
      - JUPYTER_TOKEN=dlinano
    networks:
      - dev-network

    command: jupyter lab --no-browser --ip=0.0.0.0 --port=1234 --allow-root


networks:
  dev-network:
    external: true